### ISSUE TITLE
migrate 7.0.0 to 7.2.0 Missing class referenced from: io.appmetrica.analytics.

### ISSUE THREAD

**Issue by AlexeyGodyaev** [appmetrica/appmetrica-sdk-android#10]
### 📚 AppMetrica SDK Version

7.2.0

### 📝 Description

Missing class com.google.android.gms.ads.AdValue (referenced from: io.appmetrica.analytics.modulesapi.internal.client.adrevenue.ModuleAdRevenue io.appmetrica.analytics.adrevenue.admob.v23.impl.b.a(com.google.android.gms.ads.AdValue, io.appmetrica.analytics.modulesapi.internal.client.adrevenue.ModuleAdType, com.google.android.gms.ads.ResponseInfo, java.lang.String) and 6 other contexts)
Missing class com.google.android.gms.ads.AdView (referenced from: boolean io.appmetrica.analytics.adrevenue.admob.v23.impl.d.process(java.lang.Object[]))
Missing class com.google.android.gms.ads.AdapterResponseInfo (referenced from: io.appmetrica.analytics.modulesapi.internal.client.adrevenue.ModuleAdRevenue io.appmetrica.analytics.adrevenue.admob.v23.impl.b.a(com.google.android.gms.ads.AdValue, io.appmetrica.analytics.modulesapi.internal.client.adrevenue.ModuleAdType, com.google.android.gms.ads.ResponseInfo, java.lang.String))
Missing class com.google.android.gms.ads.ResponseInfo (referenced from: io.appmetrica.analytics.modulesapi.internal.client.adrevenue.ModuleAdRevenue io.appmetrica.analytics.adrevenue.admob.v23.impl.b.a(com.google.android.gms.ads.AdValue, io.appmetrica.analytics.modulesapi.internal.client.adrevenue.ModuleAdType, com.google.android.gms.ads.ResponseInfo, java.lang.String) and 6 other contexts)
Missing class com.google.android.gms.ads.appopen.AppOpenAd (referenced from: boolean io.appmetrica.analytics.adrevenue.admob.v23.impl.c.process(java.lang.Object[]))
Missing class com.google.android.gms.ads.interstitial.InterstitialAd (referenced from: boolean io.appmetrica.analytics.adrevenue.admob.v23.impl.f.process(java.lang.Object[]))
Missing class com.google.android.gms.ads.nativead.NativeAd (referenced from: boolean io.appmetrica.analytics.adrevenue.admob.v23.impl.g.process(java.lang.Object[]))
Missing class com.google.android.gms.ads.rewarded.RewardedAd (referenced from: boolean io.appmetrica.analytics.adrevenue.admob.v23.impl.h.process(java.lang.Object[]))
Missing class com.google.android.gms.ads.rewardedinterstitial.RewardedInterstitialAd (referenced from: boolean io.appmetrica.analytics.adrevenue.admob.v23.impl.i.process(java.lang.Object[]))

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

**Comment by NesterovichAlexey** [comment]
Hi, @AlexeyGodyaev ! 

Are you getting these warnings during build and when running the app?

**Comment by AlexeyGodyaev** [comment]
> Hi, @AlexeyGodyaev !
> 
> Are you getting these warnings during build and when running the app?
build   :app:minify...ReleaseWithR8

**Comment by NesterovichAlexey** [comment]
[Internal issue](https://nda.ya.ru/t/wLD5TGXt78XVoy).

**Comment by NesterovichAlexey** [comment]
Thanks for the report. These are just warnings and they do not affect the operation of the AppMetrica SDK. In future releases, we will make sure that they do not appear.

**Comment by KondratyonokNikita** [comment]
This issue will be corrected in the next release.

These warnings can be suppressed by adding `-dontwarn com.google.android.gms.ads.**` to the consumer file of your application.

**Comment by KondratyonokNikita** [comment]
Fix committed https://github.com/appmetrica/appmetrica-sdk-android/commit/81572296e16423617822fbc19c2465d6b7b4713e
