### ISSUE TITLE
New users and sessions data in dashboard is incorrect.

### ISSUE THREAD

**Issue by VictoriaTaiwan** [appmetrica/appmetrica-sdk-android#12]
### 📚 AppMetrica SDK Version

7.2.0

### 📝 Description

Hello, thank you for your attention. Dashboard shows that I used my app 24 days ago, but last time I used it was yesterday. I have only one session shown in the dashboard. Users' count also doesn't match amount of users in Google Play.
I initialized AppMetrica in `Application.onCreate()`. My Firebase messaging version is 24.0.3.
 ```
           FirebaseApp.initializeApp(application)

            val config = AppMetricaConfig
                .newConfigBuilder(app_metrica_api_key)
                .withLocationTracking(true)
                .withSessionsAutoTrackingEnabled(true)
                .build()

            AppMetrica.activate(applicationContext, config)

            AppMetrica.enableActivityAutoTracking(application)
            AppMetricaPush.activate(applicationContext)
```

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

**Comment by alexklints** [comment]
Hello. 

You can read about the reasons for the difference between the number of users in AppMetrica and the number of installations in GooglePlay in [this section of the documentation](https://appmetrica.yandex.ru/docs/en/troubleshooting/troubleshooting#reports).

There is also event buffering on the client side of the library. That is, they are not sent instantly, but in batches. Thus, the last activity might not be sent to the server. You can use [AppMetrica#sendEventsBuffer](https://yastatic.net/s3/doc-binary/src/dev/appmetrica/ru/javadoc-7.2.2/io/appmetrica/analytics/AppMetrica.html#sendEventsBuffer()) to force it.

It will also be useful[ to enable logging in the configuration](https://yastatic.net/s3/doc-binary/src/dev/appmetrica/ru/javadoc-7.2.2/io/appmetrica/analytics/AppMetricaConfig.Builder.html#withLogs()) for debug build. The log displays information about receiving events, saving them to the local database and sending them to the server.
