### ISSUE TITLE
Choreographer  Skipped NN frames!  The application may be doing too much work on its main thread.

### ISSUE THREAD

**Issue by AlexeyGodyaev** [appmetrica/appmetrica-sdk-android#13]
### 📚 AppMetrica SDK Version

7.3.0

### 📝 Description

<img width="610" alt="image" src="https://github.com/user-attachments/assets/679f790a-66c7-46a7-8b09-2be68fd2cb87">
Pixel 8 API 34 emulator

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

**Comment by alexklints** [comment]
Hello!
Please provide a text representation of the stack trace. The attached image does not help to understand the source of the problem. Also, please tell us what device we are talking about.

Make sure that SDK logging is disabled during testing. ANR dumps from Google Play Developer Console or AppMetrica may help in the investigation.

**Comment by AlexeyGodyaev** [comment]
A couple of events in google console ('io.appmetrica.analytics:analytics:**7.2.2**'): 
1) Android 8.1 (SDK 27) Xiaomi tiare (Redmi Go) In the background
"main" tid=1 Runnable
  at io.appmetrica.analytics.impl.g6.<init> (SourceFile:15)
  at io.appmetrica.analytics.impl.Oh.b (SourceFile:4)
  at io.appmetrica.analytics.impl.Q2.a (SourceFile:39)
  at io.appmetrica.analytics.impl.m6.a (SourceFile:22)
  at io.appmetrica.analytics.impl.n6.a (SourceFile:18)
  at io.appmetrica.analytics.impl.P1.uncaughtException (SourceFile:17)
  at io.appmetrica.analytics.impl.um.uncaughtException (SourceFile:14)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1063)
  at java.lang.Thread.dispatchUncaughtException (Thread.java:1955)
  
  "IAA-DW-2" tid=34 Waiting
  at java.lang.Object.wait (Native method)
  at io.appmetrica.analytics.impl.lb.run (SourceFile:19)
  
  "IAA-CRS-3" tid=42 Timed Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos (AbstractQueuedSynchronizer.java:1061)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos (AbstractQueuedSynchronizer.java:1352)
  at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:278)
  at io.appmetrica.analytics.impl.g0.a (SourceFile:8)
  at io.appmetrica.analytics.impl.Rg.c (SourceFile:14)
  at io.appmetrica.analytics.impl.Rg.a (SourceFile:29)
  at io.appmetrica.analytics.impl.Rg.call (SourceFile:1)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.os.HandlerThread.run (HandlerThread.java:65)
  
  2) Android 8.0 (SDK 26)  HUAWEI HWANE (P20 lite)  In the background
  Native method - android.os.MessageQueue.nativePollOnce
Executing service com.___.___/io.appmetrica.analytics.internal.AppMetricaService
Stack tracing is not available.

**Comment by AlexeyGodyaev** [comment]
Pixel 8 API 34 emulator 'io.appmetrica.analytics:analytics:7.3.0'
package io.appmetrica.analytics.impl; public final class Yl extends V2 {
![image](https://github.com/user-attachments/assets/65deff1c-febb-4514-b62b-d7129070a5b0)
![image](https://github.com/user-attachments/assets/3c92bb5e-a317-4cd8-8899-be599c3dc9ec)
![image](https://github.com/user-attachments/assets/71d3296c-9e1d-41cd-8f95-674d086feba0)
You get the execution in main ?

**Comment by AlexeyGodyaev** [comment]
![image](https://github.com/user-attachments/assets/9c42c27c-3509-4bee-ac15-9db7bf5fc7ba)
package io.appmetrica.analytics.impl; public class hg extends Sg {
![image](https://github.com/user-attachments/assets/0e2d3ba0-3546-4616-beb8-b64d7c61472b)

**Comment by alexklints** [comment]
> A couple of events in google console ('io.appmetrica.analytics:analytics:**7.2.2**'):
> 
> 1. Android 8.1 (SDK 27) Xiaomi tiare (Redmi Go) In the background
>    "main" tid=1 Runnable
>    at io.appmetrica.analytics.impl.g6. (SourceFile:15)
>    at io.appmetrica.analytics.impl.Oh.b (SourceFile:4)
>    at io.appmetrica.analytics.impl.Q2.a (SourceFile:39)
>    at io.appmetrica.analytics.impl.m6.a (SourceFile:22)
>    at io.appmetrica.analytics.impl.n6.a (SourceFile:18)
>    at io.appmetrica.analytics.impl.P1.uncaughtException (SourceFile:17)
>    at io.appmetrica.analytics.impl.um.uncaughtException (SourceFile:14)
>    at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
>    at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1063)
>    at java.lang.Thread.dispatchUncaughtException (Thread.java:1955)
> 
> "IAA-DW-2" tid=34 Waiting at java.lang.Object.wait (Native method) at io.appmetrica.analytics.impl.lb.run (SourceFile:19)
> 
> "IAA-CRS-3" tid=42 Timed Waiting at java.lang.Object.wait (Native method) at java.lang.Thread.parkFor$ (Thread.java:2137) at sun.misc.Unsafe.park (Unsafe.java:358) at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230) at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos (AbstractQueuedSynchronizer.java:1061) at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos (AbstractQueuedSynchronizer.java:1352) at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:278) at io.appmetrica.analytics.impl.g0.a (SourceFile:8) at io.appmetrica.analytics.impl.Rg.c (SourceFile:14) at io.appmetrica.analytics.impl.Rg.a (SourceFile:29) at io.appmetrica.analytics.impl.Rg.call (SourceFile:1) at java.util.concurrent.FutureTask.run (FutureTask.java:266) at android.os.Handler.handleCallback (Handler.java:790) at android.os.Handler.dispatchMessage (Handler.java:99) at android.os.Looper.loop (Looper.java:164) at android.os.HandlerThread.run (HandlerThread.java:65)
> 
> 2. Android 8.0 (SDK 26)  HUAWEI HWANE (P20 lite)  In the background
>    Native method - android.os.MessageQueue.nativePollOnce
>    Executing service com._**.**_/io.appmetrica.analytics.internal.AppMetricaService
>    Stack tracing is not available.

Hi. 

Thanks for the details. There are a lot of messages, so I'll try to structure and comment. 
1. About the report from the Google Play Developer Console.  The suspension occurs at the moment of processing the cream. Unfortunately, nothing can be improved here, since the crash is processed on exactly the same thread where it happened. If we try to continue processing in the background, the process will be killed and information about the crash will be lost. So we have to save it synchronously. Hi. 

Thanks for the details. There are a lot of messages, so I'll try to structure and comment. 
1. About the report from the Google Play Developer Console.  The suspension occurs at the moment of processing the cream. Unfortunately, nothing can be improved here, since the crash is processed on exactly the same thread where it happened. If we try to continue processing in the background, the process will be killed and information about the crash will be lost. So we have to save it synchronously.

**Comment by alexklints** [comment]
> Pixel 8 API 34 emulator 'io.appmetrica.analytics:analytics:7.3.0' package io.appmetrica.analytics.impl; public final class Yl extends V2 { ![image](https://private-user-images.githubusercontent.com/28103173/391032456-65deff1c-febb-4514-b62b-d7129070a5b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzI4ODEsIm5iZiI6MTczMjg3MjU4MSwicGF0aCI6Ii8yODEwMzE3My8zOTEwMzI0NTYtNjVkZWZmMWMtZmViYi00NTE0LWI2MmItZDcxMjkwNzBhNWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDdlZGM3MDc5ZWU4MmY2OTE0NzIxNTBmNTgxNjg2NzUzZjU1NjMwYWFmOTVlZDBmZmQ1NWU3ZmVlMjg0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S9bv5OwS1WsvrjJLDADuFfCyGcat6EBgRs-uMkJA7l8) ![image](https://private-user-images.githubusercontent.com/28103173/391032608-3c92bb5e-a317-4cd8-8899-be599c3dc9ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzI4ODEsIm5iZiI6MTczMjg3MjU4MSwicGF0aCI6Ii8yODEwMzE3My8zOTEwMzI2MDgtM2M5MmJiNWUtYTMxNy00Y2Q4LTg4OTktYmU1OTljM2RjOWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZTlmMTYyODEzYjg4ODQ5N2QwYzFkN2ExYTljZDhhMjJjZDVkMTgwNWU1YTRkM2E2OTc4OWFiZDQ2ODEyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3AMnb4wVUUtycYoeb-GiGsK67qSyaXWP7GL5eOuz-ag) ![image](https://private-user-images.githubusercontent.com/28103173/391032970-71d3296c-9e1d-41cd-8f95-674d086feba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzI4ODEsIm5iZiI6MTczMjg3MjU4MSwicGF0aCI6Ii8yODEwMzE3My8zOTEwMzI5NzAtNzFkMzI5NmMtOWUxZC00MWNkLThmOTUtNjc0ZDA4NmZlYmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YzgwYjNlYWMwNjk0ZTExMTcyYTc5Yzk3Zjg5NTU0ZGQzYzU1OWQyNjYxN2FjYmFmMjc2N2ZhNzRlYzYzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YXuWxl20ODVJQKmBNJgWoGylG8OjcRBEboZociFMkJA) You get the execution in main ?

I see that you are considering a network request stack trace from the main thread. We don't go online from the main stream. Moreover, our network activity comes from a separate process. I don't see that this request has anything to do with us. We send network requests using URLConnection, not the OkHttp library. You need to understand which package the YI instance has. If you download aar and open this class as part of our SDK, you will see that there is no network activity there. There's about the following code:

```
package io.appmetrica.analytics.impl;

import android.text.TextUtils;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.VisibleForTesting;
import io.appmetrica.analytics.logger.appmetrica.internal.PublicLogger;
import java.io.UnsupportedEncodingException;

public final class Yl extends V2 {
  public Yl(int paramInt, @NonNull String paramString) {
    this(paramInt, paramString, this);
  }
  
  @VisibleForTesting(otherwise = 3)
  public final int b() {
    return this.a;
  }
  
  public Yl(int paramInt, @NonNull String paramString, @NonNull PublicLogger paramPublicLogger) {
    super(paramInt, paramString, paramPublicLogger);
  }
  
  @NonNull
  @VisibleForTesting(otherwise = 3)
  public final String a() {
    return this.b;
  }
  
  @Nullable
  public final String a(@Nullable String paramString) {
    if (!TextUtils.isEmpty(paramString))
      try {
        byte[] arrayOfByte;
        int i;
        if ((arrayOfByte = paramString.getBytes("UTF-8")).length > (
          
          i = this.a)) {
          String str;
          this(arrayOfByte, 0, i, "UTF-8");
          try {
            boolean bool = false;
            try {
              (new Object[3])[
                  bool] = this.b;
              this.c.warning("\"%s\" %s exceeded limit of %d bytes", new Object[] { null, paramString, Integer.valueOf(this.a) });
              paramString = str;
            } catch (UnsupportedEncodingException unsupportedEncodingException) {
              paramString = str;
            } 
          } catch (UnsupportedEncodingException unsupportedEncodingException) {
            paramString = str;
          } 
        } 
      } catch (UnsupportedEncodingException unsupportedEncodingException) {} 
    return paramString;
  }
}
```
This class normalizes the string by size and validates it.

You should investigate which package the Yl class has in the screenshot.

**Comment by alexklints** [comment]
> ![image](https://private-user-images.githubusercontent.com/28103173/391035065-9c42c27c-3509-4bee-ac15-9db7bf5fc7ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzI4ODEsIm5iZiI6MTczMjg3MjU4MSwicGF0aCI6Ii8yODEwMzE3My8zOTEwMzUwNjUtOWM0MmMyN2MtMzUwOS00YmVlLWFjMTUtOWRiN2JmNWZjN2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMDMwZjA3MzA0MTc5OTEyN2QxMGE0OTFhNWUzOGRmYzYyOTMzOGVkODkyOTMxMzQxNmI1MmE2OGE2ZGIyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v6kXcRmvl4B4tlnp2b84H690b6f-SGE53HvrX9Yu73E) package io.appmetrica.analytics.impl; public class hg extends Sg { ![image](https://private-user-images.githubusercontent.com/28103173/391035460-0e2d3ba0-3546-4616-beb8-b64d7c61472b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzI4ODEsIm5iZiI6MTczMjg3MjU4MSwicGF0aCI6Ii8yODEwMzE3My8zOTEwMzU0NjAtMGUyZDNiYTAtMzU0Ni00NjE2LWJlYjgtYjY0ZDdjNjE0NzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMzI2NjRmOTRmYmRmZDZlMzQ3NWNlMWMwMDlhMTQ5NTA2ZjcyNGY2OWE4ZDFkZDgyNThlNDFmMTAwODM1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NTZ89LgzNw7vygkdqIsAiSmn9NPhEcSK_kcR_Sag8cY)

You don't have a problem with these calls. You only need to pay attention to the `sendRequest` call. This particular call works with huge amounts of memory.
