### ISSUE TITLE
Crash at the detector com.yandex.mobileads.lint.appmetrica.AppMetricaIntervalVersionDetector.

### ISSUE THREAD

**Issue by sboishtyan** [appmetrica/appmetrica-sdk-android#4]
### 📚 AppMetrica SDK Version

5.3.0

### 📝 Description

I ran lint on our project and got
Gradle 8.5
Kotlin 1.9.22
AGP 8.2.2
lint 31.2.2

```
Error: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)

Message: Cannot invoke "com.android.ide.common.repository.GradleCoordinate.getVersion()" because "gradleDependency" is null

The crash seems to involve the detector com.yandex.mobileads.lint.appmetrica.AppMetricaIntervalVersionDetector.
You can try disabling it with something like this:
    android {
        lint {
            disable "AppMetricaSdkVersion"
        }
    }

Error: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)

Message: Cannot invoke "com.android.ide.common.repository.GradleCoordinate.getVersion()" because "gradleDependency" is null

The crash seems to involve the detector com.yandex.mobileads.lint.appmetrica.AppMetricaIntervalVersionDetector.
You can try disabling it with something like this:
    android {
        lint {
            disable "AppMetricaSdkVersion"
        }
```

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
Stack: NullPointerException:IntervalVersionChecker.checkDependencyVersion(IntervalVersionChecker.java:50)←GradleVersionDetector.checkDslPropertyAssignment(GradleVersionDetector.java:24)←AppMetricaIntervalVersionDetector.checkDslPropertyAssignment(AppMetricaIntervalVersionDetector.java:36)←Detector.checkDslPropertyAssignment(Detector.kt:370)←UastGradleVisitor.handleMethodCall(UastGradleVisitor.kt:171)←UastGradleVisitor.access$handleMethodCall(UastGradleVisitor.kt:39)←UastGradleVisitor$visitBuildScript$1.visitCallExpression(UastGradleVisitor.kt:45)←KotlinUFunctionCallExpression.accept(KotlinUFunctionCallExpression.kt:176)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←UBlockExpression.accept(UBlockExpression.kt:21)←ULambdaExpression.accept(ULambdaExpression.kt:40)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←KotlinUFunctionCallExpression.accept(KotlinUFunctionCallExpression.kt:180)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←UBlockExpression.accept(UBlockExpression.kt:21)←UMethod.accept(UMethod.kt:45)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←UFile.accept(UFile.kt:89)←UastLintUtilsKt.acceptSourceFile(UastLintUtils.kt:826)←UastGradleVisitor.visitBuildScript(UastGradleVisitor.kt:42)←LintDriver$checkBuildScripts$1.run(LintDriver.kt:1542)←LintClient.runReadAction(LintClient.kt:1705)←LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2903)←LintDriver.checkBuildScripts(LintDriver.kt:1526)←LintDriver.runFileDetectors(LintDriver.kt:1405)←LintDriver.checkProject(LintDriver.kt:1152)←LintDriver.checkProjectRoot(LintDriver.kt:623)←LintDriver.access$checkProjectRoot(LintDriver.kt:172)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:446)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:443)←LintDriver.doAnalyze(LintDriver.kt:502)←LintDriver.analyzeOnly(LintDriver.kt:443)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:233)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:233)←LintCliClient.run(LintCliClient.kt:275)←LintCliClient.run$default(LintCliClient.kt:258)←LintCliClient.analyzeOnly(LintCliClient.kt:233)←Main.run(Main.java:1761)←Main.run(Main.java:284)←GeneratedMethodAccessor1703.invoke(null:-1)←DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)←Method.invoke(Method.java:568)←AndroidLintWorkAction.invokeLintMainRunMethod(AndroidLintWorkAction.kt:98)←AndroidLintWorkAction.runLint(AndroidLintWorkAction.kt:87)←AndroidLintWorkAction.execute(AndroidLintWorkAction.kt:62)←DefaultWorkerServer.execute(DefaultWorkerServer.java:63)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)←ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)←NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)←AbstractWorker$1.call(AbstractWorker.java:44)←AbstractWorker$1.call(AbstractWorker.java:41)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)←DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)←DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)←AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)←NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)←DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:170)←FutureTask.run(FutureTask.java:264)←DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)←DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)←DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)←Factories$1.create(Factories.java:31)←DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:133)←DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)←DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)←Executors$RunnableAdapter.call(Executors.java:539)←FutureTask.run(FutureTask.java:264)←ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)←AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)←ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)←ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)←Thread.run(Thread.java:840) [LintError]
```

</details>

### 📦 Dependencies

It's a build classpath cause error happens in build runtime

androidx.annotation:annotation:1.5.0
androidx.databinding:databinding-common:8.2.2
androidx.databinding:databinding-compiler-common:8.2.2
com.android.databinding:baseLibrary:8.2.2
com.android.tools.analytics-library:crash:31.2.2
com.android.tools.analytics-library:protos:31.2.2
com.android.tools.analytics-library:shared:31.2.2
com.android.tools.analytics-library:tracker:31.2.2
com.android.tools.build.jetifier:jetifier-core:1.0.0-beta10
com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta10
com.android.tools.build:aapt2-proto:8.2.2-10154469
com.android.tools.build:aaptcompiler:8.2.2
com.android.tools.build:apksig:8.2.2
com.android.tools.build:apkzlib:8.2.2
com.android.tools.build:builder-model:8.2.2
com.android.tools.build:builder-test-api:8.2.2
com.android.tools.build:builder:8.2.2
com.android.tools.build:bundletool:1.15.2
com.android.tools.build:gradle-api:8.2.2
com.android.tools.build:gradle-settings-api:8.2.2
com.android.tools.build:gradle:8.2.2
com.android.tools.build:manifest-merger:31.2.2
com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api
com.android.tools.ddms:ddmlib:31.2.2
com.android.tools.layoutlib:layoutlib-api:31.2.2
com.android.tools.lint:lint-model:31.2.2
com.android.tools.lint:lint-typedef-remover:31.2.2
com.android.tools.utp:android-device-provider-ddmlib-proto:31.2.2
com.android.tools.utp:android-device-provider-gradle-proto:31.2.2
com.android.tools.utp:android-test-plugin-host-additional-test-output-proto:31.2.2
com.android.tools.utp:android-test-plugin-host-apk-installer-proto:31.2.2
com.android.tools.utp:android-test-plugin-host-coverage-proto:31.2.2
com.android.tools.utp:android-test-plugin-host-emulator-control-proto:31.2.2
com.android.tools.utp:android-test-plugin-host-logcat-proto:31.2.2
com.android.tools.utp:android-test-plugin-host-retention-proto:31.2.2
com.android.tools.utp:android-test-plugin-result-listener-gradle-proto:31.2.2
com.android.tools:annotations:31.2.2
com.android.tools:common:31.2.2
com.android.tools:dvlib:31.2.2
com.android.tools:repository:31.2.2
com.android.tools:sdk-common:31.2.2
com.android.tools:sdklib:31.2.2
com.android:signflinger:8.2.2
com.android:zipflinger:8.2.2
com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin:1.28.0
com.autonomousapps:antlr:4.10.1.5
com.autonomousapps:asm-relocated:9.6.0.0
com.autonomousapps:dependency-analysis-gradle-plugin:1.28.0
com.autonomousapps:graph-support:0.2
com.avito.android:alertino:2023.30
com.avito.android:android:2023.30
com.avito.android:api:2023.30
com.avito.android:avito-code-owners:1.43.1
com.avito.android:build-checks:2023.30
com.avito.android:build-environment:2023.30
com.avito.android:build-failer:2023.30
com.avito.android:build-metrics:2023.30
com.avito.android:build-trace:2023.30
com.avito.android:build-verdict-tasks-api:2023.30
com.avito.android:build-verdict:2023.30
com.avito.android:code-ownership-api:2023.30
com.avito.android:code-ownership-extensions:2023.30
com.avito.android:code-ownership:2023.30
com.avito.android:command-line-rx:2023.30
com.avito.android:command-line:2023.30
com.avito.android:composite-exception:2023.30
com.avito.android:coroutines-extension:2023.30
com.avito.android:critical-path-api:2023.30
com.avito.android:elastic-logger:2023.30
com.avito.android:elastic:2023.30
com.avito.android:file-storage:2023.30
com.avito.android:files:2023.30
com.avito.android:git:2023.30
com.avito.android:gradle-extensions:2023.30
com.avito.android:gradle-logger:2023.30
com.avito.android:gradle-profile:2023.30
com.avito.android:graph:2023.30
com.avito.android:graphite-config:2023.30
com.avito.android:graphite:2023.30
com.avito.android:http-statsd:2023.30
com.avito.android:impact-shared:2023.30
com.avito.android:impact:2023.30
com.avito.android:impl:2023.30
com.avito.android:instrumentation-changed-tests-finder:2023.30
com.avito.android:instrumentation-tests-dex-loader:2023.30
com.avito.android:instrumentation-tests:2023.30
com.avito.android:kotlin-ast-parser:2023.30
com.avito.android:kubernetes:2023.30
com.avito.android:logger:2023.30
com.avito.android:math:2023.30
com.avito.android:model:2023.30
com.avito.android:module-api-extraction:2023.30
com.avito.android:module-dependencies-graph:2023.30
com.avito.android:module-dependencies:2023.30
com.avito.android:module-types:2023.30
com.avito.android:network-contracts:2023.30
com.avito.android:nupokati:2023.30
com.avito.android:okhttp:2023.30
com.avito.android:plugins-configuration:2023.30
com.avito.android:pre-build:2023.30
com.avito.android:problem:2023.30
com.avito.android:process:2023.30
com.avito.android:prosector:2023.30
com.avito.android:qapps:2023.30
com.avito.android:report-api:2023.30
com.avito.android:report-processor:2023.30
com.avito.android:report-viewer-model:2023.30
com.avito.android:report-viewer-test-static-data-parser:2023.30
com.avito.android:report-viewer:2023.30
com.avito.android:result:2023.30
com.avito.android:retrace:2023.30
com.avito.android:runner-api:2023.30
com.avito.android:runner-client:2023.30
com.avito.android:runner-service:2023.30
com.avito.android:sentry-logger:2023.30
com.avito.android:series:2023.30
com.avito.android:sign-service:2023.30
com.avito.android:slack:2023.30
com.avito.android:slf4j-gradle-logger:2023.30
com.avito.android:statsd-config:2023.30
com.avito.android:statsd:2023.30
com.avito.android:tech-budget-common:2023.30
com.avito.android:tech-budget:2023.30
com.avito.android:test-annotations:2023.30
com.avito.android:test-model:2023.30
com.avito.android:test-report-artifacts:2023.30
com.avito.android:test-suite-provider:2023.30
com.avito.android:tests-summary:2023.30
com.avito.android:throwable-utils:2023.30
com.avito.android:time:2023.30
com.avito.android:tls-configuration:2023.30
com.avito.android:trace-event:2023.30
com.avito.android:waiter:2023.30
com.avito.android:worker-extensions:2023.30
com.dropbox.dependency-guard:dependency-guard:0.5.0
com.fasterxml.jackson.core:jackson-annotations:2.13.0
com.fasterxml.jackson.core:jackson-core:2.13.0
com.fasterxml.jackson.core:jackson-databind:2.13.0
com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.13.0
com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.13.0
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.0
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0
com.fasterxml.jackson:jackson-bom:2.13.0
com.github.ben-manes.caffeine:caffeine:3.1.0
com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.42.0
com.github.ben-manes:gradle-versions-plugin:0.42.0
com.github.fkorotkov:k8s-kotlin-dsl:3.1.1
com.github.mifmif:generex:1.0.2
com.github.salomonbrys.kotson:kotson:2.5.0
com.github.seratch:jslack-api-client:3.4.2
com.github.seratch:jslack-api-model:3.4.2
com.google.android:annotations:4.1.1.4
com.google.api.grpc:proto-google-common-protos:2.0.1
com.google.auth:google-auth-library-credentials:0.10.0
com.google.auth:google-auth-library-oauth2-http:0.10.0
com.google.auto.value:auto-value-annotations:1.6.2
com.google.code.findbugs:jsr305:3.0.2
com.google.code.gson:gson:2.10
com.google.crypto.tink:tink:1.7.0
com.google.dagger:dagger:2.28.3
com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:1.7.10-1.0.6
com.google.devtools.ksp:symbol-processing-api:1.9.22-1.0.17
com.google.devtools.ksp:symbol-processing-common-deps:1.9.22-1.0.17
com.google.devtools.ksp:symbol-processing-gradle-plugin:1.9.22-1.0.17
com.google.errorprone:error_prone_annotations:2.13.1
com.google.flatbuffers:flatbuffers-java:1.12.0
com.google.guava:failureaccess:1.0.1
com.google.guava:guava:31.1-jre
com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
com.google.http-client:google-http-client-jackson2:1.19.0
com.google.http-client:google-http-client:1.19.0
com.google.j2objc:j2objc-annotations:1.3
com.google.jimfs:jimfs:1.1
com.google.protobuf:protobuf-java-util:3.19.3
com.google.protobuf:protobuf-java:3.19.3
com.google.testing.platform:core-proto:0.0.8-alpha08
com.googlecode.juniversalchardet:juniversalchardet:1.0.3
com.osacky.doctor:doctor-plugin:0.8.1
com.osacky.tagger:tagger-lib:0.2
com.squareup.anvil:gradle-plugin:2.4.9
com.squareup.moshi:moshi-adapters:1.14.0
com.squareup.moshi:moshi-kotlin:1.14.0
com.squareup.moshi:moshi:1.14.0
com.squareup.okhttp3:logging-interceptor:4.10.0
com.squareup.okhttp3:okhttp-tls:4.10.0
com.squareup.okhttp3:okhttp:4.10.0
com.squareup.okio:okio-jvm:3.0.0
com.squareup.okio:okio:3.0.0
com.squareup.retrofit2:converter-gson:2.9.0
com.squareup.retrofit2:converter-moshi:2.9.0
com.squareup.retrofit2:retrofit:2.9.0
com.squareup:javapoet:1.10.0
com.squareup:javawriter:2.5.0
com.squareup:kotlinpoet:1.12.0
com.sun.activation:javax.activation:1.2.0
com.sun.istack:istack-commons-runtime:3.0.8
com.sun.xml.fastinfoset:FastInfoset:1.2.16
com.thoughtworks.xstream:xstream:1.4.17
com.timgroup:java-statsd-client:3.1.0
com.typesafe:config:1.4.1
commons-codec:commons-codec:1.15
commons-io:commons-io:2.11.0
commons-logging:commons-logging:1.2
dev.zacsweers.moshix:moshi-sealed-reflect:0.19.0
dev.zacsweers.moshix:moshi-sealed-runtime:0.19.0
dk.brics.automaton:automaton:1.11-8
io.fabric8:kubernetes-client:5.11.2
io.fabric8:kubernetes-model-admissionregistration:5.11.2
io.fabric8:kubernetes-model-apiextensions:5.11.2
io.fabric8:kubernetes-model-apps:5.11.2
io.fabric8:kubernetes-model-autoscaling:5.11.2
io.fabric8:kubernetes-model-batch:5.11.2
io.fabric8:kubernetes-model-certificates:5.11.2
io.fabric8:kubernetes-model-common:5.11.2
io.fabric8:kubernetes-model-coordination:5.11.2
io.fabric8:kubernetes-model-core:5.11.2
io.fabric8:kubernetes-model-discovery:5.11.2
io.fabric8:kubernetes-model-events:5.11.2
io.fabric8:kubernetes-model-extensions:5.11.2
io.fabric8:kubernetes-model-flowcontrol:5.11.2
io.fabric8:kubernetes-model-metrics:5.11.2
io.fabric8:kubernetes-model-networking:5.11.2
io.fabric8:kubernetes-model-node:5.11.2
io.fabric8:kubernetes-model-policy:5.11.2
io.fabric8:kubernetes-model-rbac:5.11.2
io.fabric8:kubernetes-model-scheduling:5.11.2
io.fabric8:kubernetes-model-storageclass:5.11.2
io.fabric8:kubernetes-model:5.11.0
io.fabric8:openshift-model:5.11.0
io.fabric8:zjsonpatch:0.3.0
io.github.azagniotov:ant-style-path-matcher:1.0.0
io.github.x-stream:mxparser:1.2.1
io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.23.5
io.grpc:grpc-api:1.45.1
io.grpc:grpc-context:1.45.1
io.grpc:grpc-core:1.45.1
io.grpc:grpc-netty:1.45.1
io.grpc:grpc-protobuf-lite:1.45.1
io.grpc:grpc-protobuf:1.45.1
io.grpc:grpc-stub:1.45.1
io.gsonfire:gson-fire:1.8.5
io.ktor:ktor-client-content-negotiation-jvm:2.0.3
io.ktor:ktor-client-content-negotiation:2.0.3
io.ktor:ktor-client-core-jvm:2.0.3
io.ktor:ktor-client-core:2.0.3
io.ktor:ktor-client-okhttp-jvm:2.0.3
io.ktor:ktor-client-okhttp:2.0.3
io.ktor:ktor-events-jvm:2.0.3
io.ktor:ktor-events:2.0.3
io.ktor:ktor-http-cio-jvm:2.0.3
io.ktor:ktor-http-cio:2.0.3
io.ktor:ktor-http-jvm:2.0.3
io.ktor:ktor-http:2.0.3
io.ktor:ktor-io-jvm:2.0.3
io.ktor:ktor-io:2.0.3
io.ktor:ktor-network-jvm:2.0.3
io.ktor:ktor-network:2.0.3
io.ktor:ktor-serialization-gson-jvm:2.0.3
io.ktor:ktor-serialization-gson:2.0.3
io.ktor:ktor-serialization-jvm:2.0.3
io.ktor:ktor-serialization-kotlinx-json-jvm:2.0.3
io.ktor:ktor-serialization-kotlinx-json:2.0.3
io.ktor:ktor-serialization-kotlinx-jvm:2.0.3
io.ktor:ktor-serialization-kotlinx:2.0.3
io.ktor:ktor-serialization:2.0.3
io.ktor:ktor-server-content-negotiation-jvm:2.0.3
io.ktor:ktor-server-content-negotiation:2.0.3
io.ktor:ktor-server-core-jvm:2.0.3
io.ktor:ktor-server-core:2.0.3
io.ktor:ktor-server-host-common-jvm:2.0.3
io.ktor:ktor-server-host-common:2.0.3
io.ktor:ktor-server-netty-jvm:2.0.3
io.ktor:ktor-utils-jvm:2.0.3
io.ktor:ktor-utils:2.0.3
io.ktor:ktor-websocket-serialization-jvm:2.0.3
io.ktor:ktor-websocket-serialization:2.0.3
io.ktor:ktor-websockets-jvm:2.0.3
io.ktor:ktor-websockets:2.0.3
io.kubernetes:client-java-api:13.0.1
io.kubernetes:client-java-proto:13.0.1
io.kubernetes:client-java:13.0.1
io.netty:netty-buffer:4.1.77.Final
io.netty:netty-codec-http2:4.1.77.Final
io.netty:netty-codec-http:4.1.77.Final
io.netty:netty-codec-socks:4.1.72.Final
io.netty:netty-codec:4.1.77.Final
io.netty:netty-common:4.1.77.Final
io.netty:netty-handler-proxy:4.1.72.Final
io.netty:netty-handler:4.1.77.Final
io.netty:netty-resolver:4.1.77.Final
io.netty:netty-transport-classes-epoll:4.1.77.Final
io.netty:netty-transport-classes-kqueue:4.1.77.Final
io.netty:netty-transport-native-epoll:4.1.77.Final
io.netty:netty-transport-native-kqueue:4.1.77.Final
io.netty:netty-transport-native-unix-common:4.1.77.Final
io.netty:netty-transport:4.1.77.Final
io.perfmark:perfmark-api:0.23.0
io.prometheus:simpleclient:0.11.0
io.prometheus:simpleclient_common:0.11.0
io.prometheus:simpleclient_httpserver:0.11.0
io.prometheus:simpleclient_tracer_common:0.11.0
io.prometheus:simpleclient_tracer_otel:0.11.0
io.prometheus:simpleclient_tracer_otel_agent:0.11.0
io.reactivex.rxjava3:rxjava:3.1.3
io.reactivex:rxjava:1.3.8
io.swagger:swagger-annotations:1.6.2
jakarta.activation:jakarta.activation-api:1.2.1
jakarta.xml.bind:jakarta.xml.bind-api:2.3.2
javax.annotation:javax.annotation-api:1.3.2
javax.inject:javax.inject:1
net.java.dev.jna:jna-platform:5.6.0
net.java.dev.jna:jna:5.6.0
net.sf.jopt-simple:jopt-simple:4.9
net.sf.kxml:kxml2:2.3.0
net.sf.proguard:proguard-base:6.2.2
net.sf.proguard:proguard-retrace:6.2.2
org.apache.commons:commons-collections4:4.4
org.apache.commons:commons-compress:1.21
org.apache.commons:commons-lang3:3.12.0
org.apache.commons:commons-text:1.6
org.apache.httpcomponents:httpclient:4.5.14
org.apache.httpcomponents:httpcore:4.4.16
org.apache.httpcomponents:httpmime:4.5.6
org.bitbucket.b_c:jose4j:0.7.8
org.bouncycastle:bcpkix-jdk15on:1.69
org.bouncycastle:bcprov-ext-jdk15on:1.69
org.bouncycastle:bcprov-jdk15on:1.69
org.bouncycastle:bcutil-jdk15on:1.69
org.checkerframework:checker-qual:3.21.4
org.codehaus.mojo:animal-sniffer-annotations:1.19
org.eclipse.jetty.alpn:alpn-api:1.1.3.v20160715
org.fusesource.jansi:jansi:2.4.0
org.glassfish.jaxb:jaxb-runtime:2.3.2
org.glassfish.jaxb:txw2:2.3.2
org.jdom:jdom2:2.0.6
org.jetbrains.intellij.deps:trove4j:1.0.20200330
org.jetbrains.kotlin:kotlin-android-extensions:1.9.22
org.jetbrains.kotlin:kotlin-bom:1.9.10
org.jetbrains.kotlin:kotlin-build-tools-api:1.9.22
org.jetbrains.kotlin:kotlin-compiler-embeddable:1.9.22
org.jetbrains.kotlin:kotlin-compiler-runner:1.9.22
org.jetbrains.kotlin:kotlin-daemon-client:1.9.22
org.jetbrains.kotlin:kotlin-daemon-embeddable:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugin-annotations:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugin-idea-proto:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugin-idea:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22
org.jetbrains.kotlin:kotlin-gradle-plugins-bom:1.9.22
org.jetbrains.kotlin:kotlin-klib-commonizer-api:1.9.22
org.jetbrains.kotlin:kotlin-native-utils:1.9.22
org.jetbrains.kotlin:kotlin-project-model:1.9.22
org.jetbrains.kotlin:kotlin-reflect:1.9.20
org.jetbrains.kotlin:kotlin-script-runtime:1.9.22
org.jetbrains.kotlin:kotlin-scripting-common:1.9.22
org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.9.22
org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.9.22
org.jetbrains.kotlin:kotlin-scripting-jvm:1.9.22
org.jetbrains.kotlin:kotlin-stdlib-common:1.9.20
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10
org.jetbrains.kotlin:kotlin-stdlib:1.9.20
org.jetbrains.kotlin:kotlin-tooling-core:1.9.22
org.jetbrains.kotlin:kotlin-util-io:1.9.22
org.jetbrains.kotlin:kotlin-util-klib:1.9.22
org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.2
org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.2
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.2
org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.2
org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.6.2
org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.3
org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.8.0
org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.3.3
org.jetbrains.kotlinx:kotlinx-serialization-core:1.3.3
org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.3.3
org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3
org.jetbrains:annotations:13.0
org.jgrapht:jgrapht-core:1.5.1
org.jheaps:jheaps:0.13
org.jvnet.staxex:stax-ex:1.8.1
org.ow2.asm:asm-analysis:9.2
org.ow2.asm:asm-commons:9.2
org.ow2.asm:asm-tree:9.2
org.ow2.asm:asm-util:9.2
org.ow2.asm:asm:9.2
org.reactivestreams:reactive-streams:1.0.3
org.slf4j:slf4j-api:1.7.36
org.smali:dexlib2:2.3
org.tensorflow:tensorflow-lite-metadata:0.1.0-rc2
org.yaml:snakeyaml:1.29
xerces:xercesImpl:2.12.0
xml-apis:xml-apis:1.4.01
xmlpull:xmlpull:1.1.3.1

**Comment by NesterovichAlexey** [comment]
Thank you for the report. However, I'm afraid that this issue is not related to the AppMetrica library, but rather with YandexMobileAds. I recommend contacting their support for further assistance.
