### ISSUE TITLE
sending revenue

### ISSUE THREAD

**Issue by armanhossiny** [appmetrica/appmetrica-sdk-android#8]
### 📚 AppMetrica SDK Version

7.0.0

### 📝 Description

hi
I have followed all the steps in the documentation, but in-app purchase data is not being sent to the dashboard. Please advise.

code:

>         Revenue revenue = Revenue.newBuilder(price, Currency.getInstance("IRR"))
>             .withProductID(sku)
>             .withQuantity(1)
>             // Passing the OrderID parameter in the .withPayload(String payload) method to group purchases.
>             .withPayload("{\"OrderID\":\"Identifier\", \"source\":\"Google Play\"}")
>             .build();
>
>         // Sending the Revenue instance using reporter.
>         AppMetrica.getReporter(getApplicationContext(), appId).reportRevenue(revenue);
> 
>         AppMetrica.reportRevenue(revenue);

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

**Comment by KondratyonokNikita** [comment]
Hello. Thank you for reaching out. There are a few places in your code that raise questions:

- Are you sure the variable appId contains the correct value? It should be the API_KEY.
- Make sure that the API_KEY used in the call matches the location in the UI where you expect to see the data.
- During configuration setup, specify withLogs() and check the logs; this might help identify the issue.

If these points don't help resolve the issue, contact support (https://appmetrica.yandex.ru/docs/en/troubleshooting/feedback-new). In your request, specify the essence of the problem, provide the appId value, logs, and a link to where you expect to see the data on the UI.

**Comment by armanhossiny** [comment]
hi
this my class, but not working:

```

public class Analytics {
    private static AxmolActivity app = null;
    
    private static String AppMetricaId ="app key here";

    public static void newInstance(AxmolActivity app) {
        Analytics.app = app;
        init();
    }
    public static void init(){

        //Yandex
        // Creating an extended library configuration.
        AppMetricaConfig config = AppMetricaConfig.newConfigBuilder(AppMetricaId)
                .withCrashReporting(true)
                .withNativeCrashReporting(true)
                .build();

        // Initializing the AppMetrica SDK.
        AppMetrica.activate(app.getApplicationContext(), config);

        // Automatic tracking of user activity.
        AppMetrica.enableActivityAutoTracking(app.getApplication());

        ReporterConfig reporterConfig = ReporterConfig.newConfigBuilder(AppMetricaId)
            // Setting up the configuration. For example, to enable logging.
            .withLogs()
            // ...
            .build();
        // Initializing a reporter.
        AppMetrica.activateReporter(app.getApplicationContext(), reporterConfig);

    }

    public static void logPurchased(String cat,String item,String price){
        
        long priceMain= Double.valueOf(price).longValue();


        Revenue revenue = Revenue.newBuilder(priceMain, Currency.getInstance("IRR"))
            .withProductID(item)
            .withQuantity(1)
            // Passing the OrderID parameter in the .withPayload(String payload) method to group purchases.
            .withPayload("{\"OrderID\":\"Identifier\", \"source\":\"Google Play\"}")
            .build();
        
        // Sending the Revenue instance using reporter.
        AppMetrica.getReporter(app.getApplicationContext(), AppMetricaId).reportRevenue(revenue);

        AppMetrica.reportRevenue(revenue);
        
       // AppMetrica.sendEventsBuffer();
    }
    
}

```

**Comment by KondratyonokNikita** [comment]
You should not use a reporter with the same API_KEY as the main SDK. It seems you don't need a reporter.

**Comment by armanhossiny** [comment]
Yes, that's mentioned in the documentation and I've tested it as well, but it still doesn't work.

**Comment by KondratyonokNikita** [comment]
In this case, the problem may be due to one of the following reasons:

- The event did not leave the device immediately, as it is just one event. To rule out this issue, call `AppMetrica.sendEventsBuffer()` after sending events.

- Events may not be able to leave the device due to internet issues. To test this hypothesis, you can:
  - Send regular events with a call to `AppMetrica.sendEventsBuffer()` and check if they are visible on the UI.
  - Ping the AppMetrica hosts: `ping startup.mobile.yandex.net`, `ping report.mobile.yandex.net`.
 If events are not present or hosts are not pingable, there may be an internet issue.

If the problem is not found, enable logging using:
```
AppMetricaConfig config = AppMetricaConfig.newConfigBuilder(AppMetricaId)
    .withCrashReporting(true)
    .withLogs()
    .withNativeCrashReporting(true)
    .build();
```
And send this data along with the information mentioned above to support (https://appmetrica.yandex.ru/docs/en/troubleshooting/feedback-new). Logs and API_KEY are confidential and should not be published on GitHub.
